ALTER TABLE radar_scans ADD COLUMN analytics jsonb;
ALTER TABLE jobs DROP CONSTRAINT jobs_type_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_type_check CHECK(type IN (
'FETCH_SOURCE','TRANSLATE_DOCUMENT','ANALYZE_PRODUCT','DISCOVER_FEEDBACK',
'COMPARE_OPPORTUNITIES','DISCOVER_TOPIC','RADAR_PLAN','RADAR_ANALYZE','RADAR_EXTRACT','RADAR_REPORT'));
INSERT INTO sources(id,name,kind) VALUES('appstore','App Store Reviews','reviews') ON CONFLICT DO NOTHING;
